language: android
sudo: false
jdk:
    - oraclejdk8
android:
  components:
    - tools
    - android-25
    - build-tools-25.0.2
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24
cache:
    directories:
      - "${TRAVIS_BUILD_DIR}/android/gradle/caches/"
      - "${TRAVIS_BUILD_DIR}/android/gradle/wrapper/dists/"
      - "$HOME/android/.gradle/caches/"
      - "$HOME/android/.gradle/wrapper/"
script:
  - ./gradlew build
  - ./gradlew assembleRelease
after_failure:
  # tests
  - cat app/build/reports/tests/testDebugUnitTest/index.html

  # app
  - cat app/build/reports/lint-results.xml
  - cat app/build/reports/lint-results.html
after_success:
    - bash scripts/update-apk.sh
