language: android
sudo: false
jdk:
    - oraclejdk8
android:
  components:
    - tools
    - android-27
    - build-tools-27.0.3
    - platform-tools
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
      - "${TRAVIS_BUILD_DIR}/gradle/caches/"
      - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
install:
  - echo yes | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-27"
before_script:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
script:
  - ./gradlew build
  - ./gradlew testPlayStoreDebugUnitTestCoverage
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - bash scripts/prep-key.sh
    - bash scripts/update-apk.sh
