language: android
sudo: false
jdk:
    - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
cache:
    directories:
      - node_modules
env:
    - NODE_VERSION="6.9.5"
install:
    - nvm install $NODE_VERSION
    - nvm use $NODE_VERSION
    - npm install -g ionic cordova
    - npm install
    - export PATH=$(npm bin):$PATH
script:
    - ./node_modules/.bin/tslint -c tslint.json src/**/*.ts --type-check -t stylish
    - ionic platform add android
    - ionic resources
    - ionic build android
after_success:
    - chmod +x scripts/update-apk.sh
    - sh scripts/update-apk.sh
